### ISSUE TITLE
Polls not appearing

### ISSUE THREAD

**Issue by illogicalapple** [imadeanaccount1/wasteof.plus#73] opened 2023-08-03 23:57 UTC
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/80916557/08d4a517-25b8-4b31-b99b-30bd68641f90)
I saw the poll once and then it disappeared (?)

**Comment by imadeanaccount1** [comment] 2023-08-04 00:33
Oh, okay. This sounds like it's the same bug as #58, for which the fix is in active development in #66. With this bug, you will have to reload the page to get the polls to render again, but as I said, I am working on a fix and will let you know when it's patched!

**Comment by imadeanaccount1** [comment] 2023-08-04 00:34
Duplicate of #58. (I'm closing this as further discussion will continue in #58)

**Closed by imadeanaccount1** 2023-08-04 00:34 UTC

**Comment by imadeanaccount1** [comment] 2023-08-04 19:31
@all-contributors please add @illogicalapple for bug

**Comment by illogicalapple** [comment] 2023-08-04 19:33
> @all-contributors please add @illogicalapple for bug

i feel so validated

**Comment by imadeanaccount1** [comment] 2023-08-04 19:38
> i feel so validated

that's the point of all-contributors i guess :)
