### ISSUE TITLE
User hover cards are very buggy when page is changed

### ISSUE THREAD

**Issue by mybearworld** [imadeanaccount1/wasteof.plus#51] opened 2023-07-28 16:00 UTC
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/0c07dfcc-a56d-4654-94e3-7225879b82cf)
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/130385691/c5f70be3-a1df-4459-8e19-470be510a1ae)

**Comment by imadeanaccount1** [comment] 2023-07-28 16:09
@mybearworld I've identified the cause of this bug and will try to open a PR fix within the next 2 hours. It is a bug with the new addon-loading system that I thought I had resolved before merging the Mega Update. Apparently not, i guess lol.

**Comment by imadeanaccount1** [comment] 2023-07-28 20:16
PR Created! #56

**Comment by imadeanaccount1** [comment] 2023-07-28 20:35
@mybearworld this appears to be fixed in the latest version built in the Action artifact: 
https://github.com/imadeanaccount1/wasteof.plus/actions/runs/5696025309

**Closed** 2023-07-28 20:35 UTC
Labels: bug
